"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, CheckCircle2, CircleDashed, CircleGauge, ExternalLink, RadioTower, ShieldAlert, Zap } from "lucide-react";
import { getLiveAnalysis, getMarketContext, getOpportunities, getPerformance, getRuntimeStatus, type LiveAnalysis, type Opportunity, type OpportunityResponse, type Performance } from "@/lib/api";

type Tick={price:number;change:number};
function marketEs(v?:string){const m:Record<string,string>={RISK_OFF:"MERCADO DEFENSIVO",RISK_ON:"MERCADO FAVORABLE",MIXED:"MERCADO MIXTO"};return m[String(v??"").toUpperCase()]??String(v??"SIN DATOS")}
function fmt(n?:number|null){if(n==null||!Number.isFinite(Number(n)))return"—";const x=Number(n);if(Math.abs(x)>=1000)return x.toLocaleString(undefined,{maximumFractionDigits:2});if(Math.abs(x)>=1)return x.toLocaleString(undefined,{maximumFractionDigits:6});return x.toLocaleString(undefined,{maximumSignificantDigits:8})}
function pct(n?:number|null){if(n==null||!Number.isFinite(Number(n)))return"—";const x=Number(n);return`${x>=0?"+":""}${x.toFixed(2)}%`}
function phaseEs(v?:string){const m:Record<string,string>={SIN_SETUP:"SIN SETUP",SIN_DATOS:"SIN DATOS",VIGILAR:"VIGILAR",PREACTIVACION:"PREACTIVACIÓN",VIGILAR_CONFIRMACION:"FALTA CONFIRMACIÓN",ACTIVADO:"ACTIVADO",ESPERAR_RETEST:"ESPERAR RETEST",VIGILAR_CONFLICTOS:"CONFLICTOS"};return m[String(v??"").toUpperCase()]??String(v??"—")}
function typeEs(v?:string){const m:Record<string,string>={IMPULSO_LONG:"IMPULSO LONG",IMPULSO_SHORT:"IMPULSO SHORT",REBOTE_LONG:"REBOTE LONG",RECHAZO_SHORT:"RECHAZO SHORT",SIN_SETUP:"SIN SETUP"};return m[String(v??"").toUpperCase()]??String(v??"—")}
function flatten(d:OpportunityResponse|null){if(!d)return[];const g=d.groups??{};const map=new Map<string,Opportunity>();for(const x of [...(g.elite??[]),...(g.very_strong??[]),...(g.strong??[]),...(g.watch??[]),...(g.no_trade??[])])if(!map.has(x.symbol))map.set(x.symbol,x);return Array.from(map.values())}
function checks(a:LiveAnalysis){const p=a.prediction,m=a.metrics??{},s=p?.sequence??{};if(!p)return[];const d=p.direction;return[
 {label:"Compresión",ready:Boolean(s.compressed)},
 {label:d==="LONG"?"Mínimos crecientes":"Máximos decrecientes",ready:d==="LONG"?Boolean(s.higher_lows):Boolean(s.lower_highs)},
 {label:"Volumen",ready:Number(s.volume_acceleration??m.volume_acceleration??0)>=1.15},
 {label:"OI",ready:Math.abs(Number(m.oi_change_pct??0))>=.2||Math.abs(Number(a.coinglass?.open_interest?.change_15m_pct??0))>=.2},
 {label:"Futuros",ready:d==="LONG"?Number(m.futures_delta_ratio??0)>.04:Number(m.futures_delta_ratio??0)<-.04},
 {label:"Spot",ready:d==="LONG"?Number(m.spot_delta_ratio??0)>.03:Number(m.spot_delta_ratio??0)<-.03},
 {label:"Order book",ready:d==="LONG"?Number(m.order_book_imbalance??0)>.04:Number(m.order_book_imbalance??0)<-.04},
 {label:"BTC",ready:d==="LONG"?m.btc_trend!=="BEARISH":m.btc_trend!=="BULLISH"},
 {label:"Trigger",ready:Boolean(p.trigger_hit)&&!Boolean(s.chase_risk)},
]}

export default function HomeCommandCenter(){
 const [opp,setOpp]=useState<OpportunityResponse|null>(null);const [market,setMarket]=useState<any>(null);const [perf,setPerf]=useState<Performance|null>(null);const [runtime,setRuntime]=useState<any>(null);const [analysis,setAnalysis]=useState<LiveAnalysis|null>(null);const ticks=useRef(new Map<string,Tick>());const [,paint]=useState(0);
 useEffect(()=>{let dead=false;async function load(){const [o,m,p,r]=await Promise.allSettled([getOpportunities(),getMarketContext(),getPerformance(),getRuntimeStatus()]);if(dead)return;if(o.status==="fulfilled")setOpp(o.value);if(m.status==="fulfilled")setMarket(m.value);if(p.status==="fulfilled")setPerf(p.value);if(r.status==="fulfilled")setRuntime(r.value)}load();const t=setInterval(load,10000);return()=>{dead=true;clearInterval(t)}},[]);
 const items=useMemo(()=>flatten(opp).sort((a,b)=>(b.contextual_score??b.setup_score)-(a.contextual_score??a.setup_score)),[opp]);const featured=items.find(x=>x.state==="READY")??items.find(x=>x.state==="PREPARING")??items.find(x=>x.state==="WATCH")??items[0];
 useEffect(()=>{let dead=false;if(!featured?.symbol)return;async function load(){try{const a=await getLiveAnalysis(featured.symbol);if(!dead)setAnalysis(a)}catch{}}load();const t=setInterval(load,20000);return()=>{dead=true;clearInterval(t)}},[featured?.symbol]);
 useEffect(()=>{let dead=false;let ws=new WebSocket("wss://fstream.binance.com/ws/!ticker@arr");ws.onmessage=e=>{try{const p=JSON.parse(e.data);if(Array.isArray(p))for(const i of p){const s=String(i.s??"");if(s.endsWith("USDT"))ticks.current.set(s,{price:Number(i.c??0),change:Number(i.P??0)})}}catch{}};const t=setInterval(()=>!dead&&paint(x=>x+1),500);return()=>{dead=true;clearInterval(t);try{ws.close()}catch{}}},[]);
 const p=analysis?.prediction;const c=analysis?checks(analysis):[];const ready=c.filter(x=>x.ready).length;const isReady=analysis?.state==="READY"&&p?.phase==="ACTIVADO";const tick=featured?ticks.current.get(featured.symbol):undefined;
 return <main className="mx-auto min-h-screen max-w-[1680px] px-3 py-4 sm:px-5 lg:px-6">
  <header className="mb-4 flex flex-col gap-4 border-b border-slate-800/70 pb-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.18em] text-emerald-400"><RadioTower size={14}/> Centro de mando</div><h1 className="mt-1 text-4xl font-black tracking-tight text-white">ExplodeX</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Detecta preparación previa, activa solo con trigger confirmado y administra PAPER con stop estructural, TP y time-stop.</p></div><div className="flex gap-2"><Link href="/terminal" className="rounded-xl border border-emerald-500/25 bg-emerald-500/[.07] px-4 py-2 text-xs font-black text-emerald-200">Abrir Terminal</Link><Link href="/scanner" className="rounded-xl border border-slate-800 bg-slate-950/60 px-4 py-2 text-xs font-black text-slate-300">Abrir Scanner</Link></div></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat icon={<CircleGauge size={15}/>} label="Mercado" value={marketEs(market?.regime)}/><Stat icon={<Activity size={15}/>} label="Runtime" value={runtime?.scanner?.last_ok===false?"DEGRADADO":"ONLINE"}/><Stat icon={<BarChart3 size={15}/>} label="Win rate PAPER" value={perf?.win_rate_pct==null?"Sin muestra":`${perf.win_rate_pct}%`}/><Stat icon={<BarChart3 size={15}/>} label="PnL PAPER" value={perf?`${perf.net_pnl_usdt.toFixed(2)} USDT`:"—"}/><Stat icon={<Zap size={15}/>} label="Señales visibles" value={String(items.length)}/></section>
  <section className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.35fr)_470px]">
   <div className="terminal-panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 p-4"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-slate-500">Prioridad actual</div><h2 className="mt-1 text-xl font-black text-white">{featured?"Mejor preparación detectada":"Sin setup fuerte ahora"}</h2></div><span className={`status-pill ${isReady?"status-ready":"status-watch"}`}>{isReady?"OPERABLE":"SOLO VIGILAR"}</span></div>{featured&&analysis&&p?<div className="p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-3xl font-black text-white">{featured.symbol}</h3><span className={`status-pill ${p.direction==="LONG"?"status-long":"status-short"}`}>{p.direction==="LONG"?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {typeEs(p.type)}</span><span className={`status-pill ${p.phase==="ACTIVADO"?"status-ready":p.phase==="PREACTIVACION"?"status-watch":"status-neutral"}`}>{phaseEs(p.phase)}</span></div><div className="mt-2 flex gap-4 text-xs text-slate-500"><span>Precio <b className="mono-number text-white">{fmt(tick?.price??analysis.current_price)}</b></span><span className={(tick?.change??0)>=0?"text-emerald-400":"text-rose-400"}>{pct(tick?.change)}</span></div></div><Link href={`/coin/${featured.symbol}`} className="inline-flex items-center gap-2 rounded-xl border border-slate-800 px-3 py-2 text-xs font-bold text-slate-300">Plan completo <ExternalLink size={13}/></Link></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Mini label="Preparación" value={`${p.preactivation_score.toFixed(1)}/100`} accent/><Mini label="Setup" value={`${analysis.setup_score.toFixed(1)}/100`}/><Mini label="Riesgo" value={`${analysis.risk_score.toFixed(1)}/100`}/><Mini label="Condiciones" value={`${ready}/${c.length}`}/></div><div className={`mt-4 rounded-2xl border p-4 ${isReady?"border-emerald-500/30 bg-emerald-500/[.07]":"border-amber-500/25 bg-amber-500/[.045]"}`}><div className={`text-xl font-black ${isReady?"text-emerald-300":"text-amber-100"}`}>{isReady?"READY · ENTRADA HABILITADA":"NO ENTRAR TODAVÍA"}</div><p className="mt-1 text-xs leading-5 text-slate-400">{isReady?"Secuencia previa activada, dirección alineada y precio dentro del plan.":"Esperar trigger y confirmaciones. Si se va sin nosotros, no perseguir; esperar retest."}</p></div><div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-6"><Plan label="Trigger" value={p.trigger_price}/><Plan label="Entrada" value={`${fmt(p.entry_low)}–${fmt(p.entry_high)}`}/><Plan label="Stop" value={p.stop_loss} danger/><Plan label="TP1" value={p.tp1} good/><Plan label="TP2" value={p.tp2} good/><Plan label="TP3" value={p.tp3} good/></div></div>:<div className="p-12 text-center text-sm text-slate-600">El scanner todavía no tiene una preparación suficientemente clara.</div>}</div>
   <aside className="terminal-panel p-4"><div className="mb-3 flex items-center justify-between"><div className="font-black text-white">Qué falta para activar</div><div className="text-xs font-black text-emerald-300">{ready}/{c.length}</div></div><div className="space-y-2">{c.length?c.map(x=><div key={x.label} className={`flex items-center justify-between rounded-xl border px-3 py-2.5 ${x.ready?"border-emerald-500/15 bg-emerald-500/[.04]":"border-slate-800 bg-slate-950/40"}`}><div className={`flex items-center gap-2 text-xs ${x.ready?"text-emerald-200":"text-slate-400"}`}>{x.ready?<CheckCircle2 size={14}/>:<CircleDashed size={14}/>} {x.label}</div><span className="text-[10px] text-slate-600">{x.ready?"LISTO":"FALTA"}</span></div>):<div className="py-8 text-center text-xs text-slate-600">Sin predicción seleccionada.</div>}</div>{Boolean(p?.sequence?.chase_risk)&&<div className="mt-3 flex items-center gap-2 rounded-xl border border-rose-500/20 bg-rose-500/[.05] p-3 text-xs text-rose-200"><ShieldAlert size={15}/> Precio ya se alejó: esperar retest.</div>}</aside>
  </section>
  <section className="mt-4 terminal-panel overflow-hidden"><div className="border-b border-slate-800 px-4 py-3"><div className="font-black text-white">Radar rápido</div><div className="text-[10px] text-slate-600">Top setups del ranking actual</div></div><div className="grid gap-px bg-slate-800/30 md:grid-cols-2 xl:grid-cols-4">{items.slice(0,8).map(x=>{const t=ticks.current.get(x.symbol);return <Link href={`/coin/${x.symbol}`} key={x.id} className="bg-[#07111d] p-4 hover:bg-slate-900/70"><div className="flex items-center justify-between"><b className="text-white">{x.symbol}</b><span className={x.direction==="LONG"?"text-emerald-400":"text-rose-400"}>{x.direction}</span></div><div className="mt-2 flex items-end justify-between"><div className="mono-number text-lg font-black text-white">{fmt(t?.price??x.current_price)}</div><div className={(t?.change??0)>=0?"text-xs text-emerald-400":"text-xs text-rose-400"}>{pct(t?.change)}</div></div><div className="mt-2 text-[10px] text-slate-600">Score {(x.contextual_score??x.setup_score).toFixed(1)} · riesgo {(x.contextual_risk_score??x.risk_score).toFixed(1)} · {x.state}</div></Link>})}</div></section>
 </main>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="terminal-panel p-3"><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.1em] text-slate-600">{icon}{label}</div><div className="mt-2 text-lg font-black text-white">{value}</div></div>}
function Mini({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <div className="rounded-xl border border-slate-800 bg-slate-950/45 p-3"><div className="text-[9px] uppercase tracking-[.1em] text-slate-600">{label}</div><div className={`mt-1 text-sm font-black ${accent?"text-cyan-300":"text-white"}`}>{value}</div></div>}
function Plan({label,value,danger=false,good=false}:{label:string;value:number|string|undefined;danger?:boolean;good?:boolean}){return <div className="rounded-xl border border-slate-800 bg-slate-950/50 p-2.5"><div className="text-[9px] text-slate-600">{label}</div><div className={`mono-number mt-1 text-[11px] font-black ${danger?"text-rose-300":good?"text-emerald-300":"text-white"}`}>{typeof value==="number"?fmt(value):value??"—"}</div></div>}
