"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, Clock3, Coins, ShieldCheck } from "lucide-react";

const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "") || "";

type Position = { id:number; symbol:string; side:"LONG"|"SHORT"; leverage:number; entry_price:number; mark_price:number; stop_loss:number; take_profit:number; margin_used:number; unrealized_pnl:number; opened_at:string };
type Summary = { paper_only:boolean; starting_balance:number; cash_balance:number; unrealized_pnl:number; equity:number; realized_pnl:number; total_costs:number; open_positions:Position[]; closed_trades:number; winners:number; losers:number; win_rate_pct:number|null; assumptions?:Record<string,number> };
type HistoryRow = { id:number; symbol:string; side:string; leverage:number; entry_price:number; exit_price:number|null; opened_at:string; closed_at:string|null; exit_reason:string|null; gross_pnl:number|null; net_pnl:number|null; fees:number|null; slippage:number|null; funding_estimate:number|null };

const money=(v?:number|null)=>v==null||!Number.isFinite(Number(v))?"—":`${Number(v).toFixed(2)} USDT`;
const px=(v?:number|null)=>v==null||!Number.isFinite(Number(v))?"—":Number(v).toLocaleString(undefined,{maximumSignificantDigits:9});
const dt=(v?:string|null)=>!v?"—":new Date(v).toLocaleString("es-GT",{dateStyle:"short",timeStyle:"short"});

export default function PaperPortfolioLab(){
 const [summary,setSummary]=useState<Summary|null>(null); const [history,setHistory]=useState<HistoryRow[]>([]); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let dead=false; async function load(){if(!BASE_URL){setError("NEXT_PUBLIC_API_BASE_URL no configurada");return;} try{const [s,h]=await Promise.all([fetch(`${BASE_URL}/api/v1/paper-trading/summary`,{cache:"no-store"}),fetch(`${BASE_URL}/api/v1/paper-trading/history?limit=100`,{cache:"no-store"})]); if(!s.ok||!h.ok)throw new Error(`Backend ${!s.ok?s.status:h.status}`); const sj=await s.json(); const hj=await h.json(); if(!dead){setSummary(sj);setHistory(hj.rows??[]);setError(null)}}catch(e){if(!dead)setError(e instanceof Error?e.message:String(e))}} load(); const t=window.setInterval(load,10000); return()=>{dead=true;window.clearInterval(t)}},[]);
 if(error)return <div className="terminal-panel border-rose-500/20 p-5 text-sm text-rose-200">PAPER Portfolio temporalmente no disponible: {error}</div>;
 if(!summary)return <div className="terminal-panel p-5 text-sm text-slate-500"><Activity className="mr-2 inline animate-pulse" size={14}/>Cargando cuenta PAPER de 1,000 USDT…</div>;
 const delta=summary.equity-summary.starting_balance;
 return <div className="space-y-5">
  <section className="rounded-3xl border border-amber-400/25 bg-amber-400/[.05] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.15em] text-amber-300"><ShieldCheck size={16}/> SIMULACIÓN · NO DINERO REAL</div><div className="mt-1 text-sm text-slate-400">ExplodeX abre únicamente señales autorizadas por el Heart. El saldo, apalancamiento, PnL y costos son virtuales.</div></div><span className="rounded-full border border-amber-400/25 px-3 py-1 text-[10px] font-black text-amber-200">HEART RISK ADAPTIVE</span></div></section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Stat label="Capital inicial" value={money(summary.starting_balance)}/><Stat label="Equity actual" value={money(summary.equity)} tone={delta>=0?"good":"bad"}/><Stat label="Resultado total" value={money(delta)} tone={delta>=0?"good":"bad"}/><Stat label="PnL realizado" value={money(summary.realized_pnl)} tone={summary.realized_pnl>=0?"good":"bad"}/><Stat label="PnL abierto" value={money(summary.unrealized_pnl)} tone={summary.unrealized_pnl>=0?"good":"bad"}/><Stat label="Costos simulados" value={money(summary.total_costs)}/></section>
  <section className="grid gap-3 lg:grid-cols-[1fr_.42fr]"><div><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-white">Posiciones que ExplodeX decidió abrir</h2><span className="text-[10px] text-slate-600">actualiza cada 10 s</span></div><div className="grid gap-3 xl:grid-cols-2">{summary.open_positions.map(p=><article key={p.id} className="terminal-panel p-4"><div className="flex items-start justify-between gap-3"><div><Link href={`/coin/${p.symbol}`} className="text-xl font-black text-white hover:text-cyan-300">{p.symbol}</Link><div className={`mt-1 inline-flex items-center gap-1 text-xs font-black ${p.side==="LONG"?"text-emerald-400":"text-rose-400"}`}>{p.side==="LONG"?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {p.side}</div></div><div className="rounded-xl border border-slate-700 px-3 py-1.5 text-sm font-black text-cyan-200">{p.leverage}x</div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Cell label="Entrada real simulada" value={px(p.entry_price)}/><Cell label="Mark" value={px(p.mark_price)}/><Cell label="STOP" value={px(p.stop_loss)} bad/><Cell label="TP" value={px(p.take_profit)} good/></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs"><span className="text-slate-500">Margen {money(p.margin_used)}</span><span className={`font-black ${p.unrealized_pnl>=0?"text-emerald-300":"text-rose-300"}`}>{p.unrealized_pnl>=0?"+":""}{money(p.unrealized_pnl)}</span></div><div className="mt-2 text-[10px] text-slate-600"><Clock3 className="mr-1 inline" size={11}/>Abierta {dt(p.opened_at)}</div></article>)}{!summary.open_positions.length&&<div className="terminal-panel col-span-full p-8 text-center text-sm text-slate-600">Sin posiciones abiertas. PAPER espera una autorización ejecutable del Heart.</div>}</div></div>
  <aside className="terminal-panel p-4"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.12em] text-cyan-300"><Coins size={14}/> Reglas PAPER</div><div className="mt-4 space-y-2 text-xs leading-5 text-slate-400"><p>Riesgo base: <b className="text-white">{summary.assumptions?.risk_per_trade_pct??1}%</b> del saldo.</p><p>Riesgo adaptativo del Heart: <b className="text-white">aprox. 0.25%–1.50%</b> según convicción, R/R, riesgo y consenso temporal.</p><p>Máximo: <b className="text-white">{summary.assumptions?.max_open_positions??3}</b> posiciones simultáneas.</p><p>En modo defensivo se reduce fuertemente la exposición y no se permiten entradas agresivas tempranas.</p><p>Taker asumido: <b className="text-white">{summary.assumptions?.taker_fee_pct_per_side??0.05}%</b> por lado.</p><p>Slippage asumido: <b className="text-white">{summary.assumptions?.slippage_pct_per_side??0.02}%</b> por lado.</p><p>Funding estimado: <b className="text-white">{summary.assumptions?.funding_estimate_pct_per_8h??0.01}% / 8h</b>.</p></div><div className="mt-4 rounded-xl border border-slate-800 bg-slate-950/40 p-3 text-[10px] leading-5 text-slate-500">Las comisiones, slippage y funding son supuestos de investigación; no representan una factura exacta de Binance.</div></aside></section>
  <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-white">Historial automático</h2><div className="text-xs text-slate-500">{summary.closed_trades} cerradas · {summary.win_rate_pct==null?"sin muestra":`${summary.win_rate_pct}% ganadoras`}</div></div><div className="terminal-panel overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="border-b border-slate-800 text-[9px] uppercase tracking-[.1em] text-slate-600"><tr><th className="px-3 py-2 text-left">Activo</th><th>Dir.</th><th>Lev.</th><th>Entrada</th><th>Salida</th><th>Neto</th><th>Costos</th><th className="px-3 text-left">Abierta</th><th className="px-3 text-left">Cerrada</th><th className="text-left">Cierre</th></tr></thead><tbody>{history.map(r=>{const costs=Number(r.fees??0)+Number(r.slippage??0)+Number(r.funding_estimate??0);return <tr key={r.id} className="border-t border-slate-900"><td className="px-3 py-3 font-black text-white">{r.symbol}</td><td className={`px-3 py-3 font-bold ${r.side==="LONG"?"text-emerald-400":"text-rose-400"}`}>{r.side}</td><td className="px-3 py-3 text-center">{r.leverage}x</td><td className="px-3 py-3 text-right font-mono">{px(r.entry_price)}</td><td className="px-3 py-3 text-right font-mono">{px(r.exit_price)}</td><td className={`px-3 py-3 text-right font-black ${Number(r.net_pnl??0)>=0?"text-emerald-400":"text-rose-400"}`}>{money(r.net_pnl)}</td><td className="px-3 py-3 text-right text-slate-500">{money(costs)}</td><td className="whitespace-nowrap px-3 py-3 text-left text-slate-500">{dt(r.opened_at)}</td><td className="whitespace-nowrap px-3 py-3 text-left text-slate-500">{dt(r.closed_at)}</td><td className="px-3 py-3 text-left text-slate-400">{String(r.exit_reason??"—").replaceAll("_"," ")}</td></tr>})}</tbody></table></div>{!history.length&&<div className="p-8 text-center text-sm text-slate-600">Todavía no hay operaciones PAPER cerradas.</div>}</div></section>
 </div>
}
function Stat({label,value,tone}:{label:string;value:string;tone?:"good"|"bad"}){return <div className="terminal-panel p-3"><div className="text-[9px] font-bold uppercase tracking-[.1em] text-slate-600">{label}</div><div className={`mt-2 text-lg font-black ${tone==="good"?"text-emerald-300":tone==="bad"?"text-rose-300":"text-white"}`}>{value}</div></div>}
function Cell({label,value,good=false,bad=false}:{label:string;value:string;good?:boolean;bad?:boolean}){return <div className="rounded-xl border border-slate-800 bg-slate-950/45 p-2.5"><div className="text-[9px] text-slate-600">{label}</div><div className={`mt-1 font-mono text-xs font-black ${good?"text-emerald-300":bad?"text-rose-300":"text-white"}`}>{value}</div></div>}
