"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Clock3, WalletCards } from "lucide-react";
import { getPaperHistory, getPaperOpen, getPerformance, type PaperTrade, type Performance } from "@/lib/api";

function fmt(v?:number|null){if(v==null||!Number.isFinite(Number(v)))return"—";return Number(v).toLocaleString(undefined,{maximumSignificantDigits:8})}
function reason(v?:string|null){return({TIME_STOP:"TIME STOP · sin seguimiento",MAX_DURATION:"DURACIÓN MÁXIMA",STOP_LOSS:"STOP LOSS",BREAKEVEN_STOP:"STOP EN BREAK-EVEN",TP2:"TP2 ALCANZADO"} as Record<string,string>)[String(v??"")]??String(v??"—").replaceAll("_"," ")}

export default function PaperLiveBoard(){
 const [open,setOpen]=useState<PaperTrade[]>([]);const [history,setHistory]=useState<PaperTrade[]>([]);const [perf,setPerf]=useState<Performance|null>(null);const [connected,setConnected]=useState(true);
 useEffect(()=>{let dead=false;async function load(){const [o,h,p]=await Promise.allSettled([getPaperOpen(),getPaperHistory(),getPerformance()]);if(dead)return;if(o.status==="fulfilled")setOpen(o.value);if(h.status==="fulfilled")setHistory(h.value);if(p.status==="fulfilled")setPerf(p.value);setConnected(o.status==="fulfilled"&&h.status==="fulfilled")}load();const t=setInterval(load,5000);return()=>{dead=true;clearInterval(t)}},[]);
 return <>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Estado" value={connected?"EN VIVO":"DEGRADADO"}/><Stat label="Abiertas" value={String(open.length)}/><Stat label="Cerradas" value={String(perf?.closed_trades??0)}/><Stat label="PnL neto" value={perf?`${perf.net_pnl_usdt.toFixed(2)} USDT`:"—"}/><Stat label="Win rate" value={perf?.win_rate_pct==null?"Sin muestra":`${perf.win_rate_pct}%`}/></section>
  <section className="mt-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-white">Operaciones abiertas</h2><span className="text-[10px] text-slate-600">refresco 5 s</span></div><div className="grid gap-3 xl:grid-cols-2">{open.map(t=><article key={t.id} className="terminal-panel p-4"><div className="flex items-start justify-between"><div><Link href={`/coin/${t.symbol}`} className="text-xl font-black text-white hover:text-emerald-300">{t.symbol}</Link><div className={`mt-1 inline-flex items-center gap-1 text-xs font-black ${t.direction==="LONG"?"text-emerald-400":"text-rose-400"}`}>{t.direction==="LONG"?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {t.direction}</div></div><span className="status-pill status-ready">{t.status}</span></div><div className="mt-4 grid grid-cols-4 gap-2"><Cell label="Entrada" value={fmt(t.entry_price)}/><Cell label="Stop" value={fmt(t.stop_loss)} danger/><Cell label="TP1" value={fmt(t.tp1)} good/><Cell label="TP2" value={fmt(t.tp2)} good/></div><div className="mt-3 flex flex-wrap gap-4 text-[10px] text-slate-500"><span>Riesgo {t.risk_pct??"—"}%</span><span>Apalancamiento virtual {t.leverage?.toFixed(2)??"—"}x</span><span className="inline-flex items-center gap-1"><Clock3 size={11}/> abierto {new Date(t.opened_at).toLocaleString("es-GT")}</span></div></article>)}{!open.length&&<div className="terminal-panel col-span-full p-8 text-center text-sm text-slate-600">No hay operaciones PAPER abiertas. El motor solo abre desde READY y dentro de la zona de entrada.</div>}</div></section>
  <section className="mt-5"><h2 className="mb-3 text-lg font-black text-white">Historial y motivo de salida</h2><div className="terminal-panel overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="border-b border-slate-800 bg-slate-950/30 text-[9px] uppercase tracking-[.1em] text-slate-600"><tr><th className="px-3 py-2 text-left">Moneda</th><th className="px-3 py-2">Dir.</th><th className="px-3 py-2 text-right">Entrada</th><th className="px-3 py-2 text-right">Salida</th><th className="px-3 py-2 text-right">PnL</th><th className="px-3 py-2 text-right">R</th><th className="px-3 py-2 text-left">Motivo</th></tr></thead><tbody>{history.map(t=><tr key={t.id} className="border-t border-slate-900"><td className="px-3 py-3 font-black text-white">{t.symbol}</td><td className={`px-3 py-3 font-bold ${t.direction==="LONG"?"text-emerald-400":"text-rose-400"}`}>{t.direction}</td><td className="mono-number px-3 py-3 text-right text-slate-400">{fmt(t.entry_price)}</td><td className="mono-number px-3 py-3 text-right text-slate-400">{fmt(t.exit_price)}</td><td className={`px-3 py-3 text-right font-black ${(t.pnl_usdt??0)>=0?"text-emerald-400":"text-rose-400"}`}>{t.pnl_usdt?.toFixed(2)??"—"}</td><td className="px-3 py-3 text-right text-slate-300">{t.r_multiple?.toFixed(2)??"—"}</td><td className="px-3 py-3 text-slate-400">{reason(t.close_reason)}</td></tr>)}</tbody></table></div>{!history.length&&<div className="p-8 text-center text-sm text-slate-600">Todavía no hay muestra cerrada.</div>}</div></section>
 </>
}
function Stat({label,value}:{label:string;value:string}){return <div className="terminal-panel p-3"><div className="text-[9px] font-bold uppercase tracking-[.1em] text-slate-600">{label}</div><div className="mt-2 text-lg font-black text-white">{value}</div></div>}
function Cell({label,value,danger=false,good=false}:{label:string;value:string;danger?:boolean;good?:boolean}){return <div className="rounded-xl border border-slate-800 bg-slate-950/45 p-2.5"><div className="text-[9px] text-slate-600">{label}</div><div className={`mono-number mt-1 text-xs font-black ${danger?"text-rose-300":good?"text-emerald-300":"text-white"}`}>{value}</div></div>}
