"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Activity, BrainCircuit, TrendingDown, TrendingUp } from "lucide-react";

const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "") || "";

type Row = { id:string; symbol:string; created_at:string; direction:string; state:string; setup_score:number; risk_score:number; reason:any };
type Point = { at:number; pre:number; setup:number; phase:string; direction:string };

function parse(value:any){if(value&&typeof value==="object")return value;if(typeof value==="string"){try{return JSON.parse(value)}catch{return{}}}return{}}

export default function PreparationMemory(){
 const [rows,setRows]=useState<Row[]>([]);
 useEffect(()=>{let dead=false;async function load(){if(!BASE_URL)return;try{const r=await fetch(`${BASE_URL}/api/v1/signals/active?limit=100`,{cache:"no-store"});if(!r.ok)return;const d=await r.json();if(!dead)setRows(d)}catch{}}load();const t=setInterval(load,10000);return()=>{dead=true;clearInterval(t)}},[]);
 const groups=useMemo(()=>{const g=new Map<string,Point[]>();for(const row of rows){const reason=parse(row.reason),p=parse(reason.prediction);const pre=Number(p.preactivation_score??reason?.metrics?.pre_move_score??0);if(!pre)continue;const list=g.get(row.symbol)??[];list.push({at:new Date(row.created_at).getTime(),pre,setup:Number(row.setup_score??0),phase:String(p.phase??row.state),direction:String(p.direction??row.direction)});g.set(row.symbol,list)}const out=[] as Array<{symbol:string;points:Point[];velocity:number;accelerating:boolean;cooling:boolean}>;for(const [symbol,list] of g){list.sort((a,b)=>a.at-b.at);const points=list.slice(-6),values=points.map(x=>x.pre);const velocity=values.length>1?values[values.length-1]-values[0]:0;const accelerating=values.length>=3&&values[values.length-1]>values[values.length-2]&&values[values.length-2]>values[values.length-3];const cooling=values.length>=3&&values[values.length-1]<values[values.length-2]&&values[values.length-2]<values[values.length-3];out.push({symbol,points,velocity,accelerating,cooling})}return out.sort((a,b)=>(Number(b.accelerating)-Number(a.accelerating))||b.velocity-a.velocity||((b.points.at(-1)?.pre??0)-(a.points.at(-1)?.pre??0))).slice(0,8)},[rows]);
 return <section className="terminal-panel mt-4 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 p-4"><div><div className="flex items-center gap-2 text-sm font-black text-white"><BrainCircuit size={16} className="text-violet-300"/> Memoria de preparación</div><div className="mt-1 text-[10px] text-slate-600">Evolución entre ciclos del scanner · aproximación a reconocimiento estadístico de patrón</div></div><span className="status-pill status-neutral"><Activity size={11}/> HISTORIA</span></div><div className="grid gap-px bg-slate-800/30 md:grid-cols-2 xl:grid-cols-4">{groups.map(g=>{const last=g.points.at(-1);return <Link href={`/coin/${g.symbol}`} key={g.symbol} className="bg-[#07111d] p-4 hover:bg-slate-900/70"><div className="flex items-center justify-between gap-2"><div><div className="font-black text-white">{g.symbol}</div><div className={`mt-1 text-[10px] font-bold ${last?.direction==="LONG"?"text-emerald-400":"text-rose-400"}`}>{last?.direction} · {String(last?.phase??"—").replaceAll("_"," ")}</div></div>{g.accelerating?<span className="inline-flex items-center gap-1 text-[10px] font-black text-emerald-300"><TrendingUp size={13}/> ACELERANDO</span>:g.cooling?<span className="inline-flex items-center gap-1 text-[10px] font-black text-rose-300"><TrendingDown size={13}/> ENFRIANDO</span>:<span className="text-[10px] text-slate-600">ESTABLE</span>}</div><div className="mt-4 flex items-end gap-1">{g.points.map((p,i)=><div key={`${p.at}-${i}`} className="flex-1"><div className="rounded-sm bg-violet-400/25" style={{height:`${Math.max(4,Math.min(42,p.pre*.42))}px`}}/><div className="mt-1 text-center text-[9px] font-bold text-slate-500">{p.pre.toFixed(0)}</div></div>)}</div><div className="mt-3 flex justify-between text-[10px] text-slate-600"><span>{g.points.length} ciclos</span><span className={g.velocity>=0?"text-emerald-400":"text-rose-400"}>{g.velocity>=0?"+":""}{g.velocity.toFixed(1)}</span></div></Link>})}{!groups.length&&<div className="col-span-full p-8 text-center text-xs text-slate-600">Esperando varios ciclos para construir memoria de preparación.</div>}</div><div className="border-t border-slate-800 px-4 py-3 text-[10px] leading-4 text-slate-600">“Acelerando” significa que el score previo ha subido en ciclos consecutivos; no es probabilidad de ganar ni reemplaza trigger, stop y gestión de riesgo.</div></section>
}
