"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, FlaskConical, ShieldCheck } from "lucide-react";

const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "") || "";

type Cohort={trade_class:string;horizon_minutes:number;sample:number;tp1_first:number;stop_first:number;tp1_before_stop_rate_pct:number|null;avg_mfe_pct:number|null;avg_mae_abs_pct:number|null;avg_directional_return_pct:number|null};
type Report={research_status:string;minimum_research_sample:number;observations:number;horizon_results:number;labeled_60m:number;trade_class_counts:Record<string,number>;actionable_share_pct:number;cohorts:Cohort[];diagnostics:{false_yes_60m_stop_first:number;missed_opportunity_proxy_60m:number};note:string};
const pct=(v?:number|null,d=1)=>v==null?"—":`${Number(v).toFixed(d)}%`;
const classes=["TRADE_NOW","TRADE_SOON","WATCHLIST","NO_TRADE"];

export default function ValidationLab(){
 const [data,setData]=useState<Report|null>(null);const[error,setError]=useState<string|null>(null);
 useEffect(()=>{let dead=false;async function load(){if(!BASE_URL){setError("NEXT_PUBLIC_API_BASE_URL no configurada");return}try{const r=await fetch(`${BASE_URL}/api/v1/validation/report`,{cache:"no-store"});if(!r.ok)throw new Error(`Backend ${r.status}`);const j=await r.json();if(!dead){setData(j);setError(null)}}catch(e){if(!dead)setError(e instanceof Error?e.message:String(e))}}load();const t=setInterval(load,30000);return()=>{dead=true;clearInterval(t)}},[]);
 const rows=useMemo(()=>data?.cohorts?.filter(r=>classes.includes(r.trade_class))??[],[data]);
 if(error)return <div className="terminal-panel border-rose-500/20 p-5 text-sm text-rose-200">Validation Lab temporalmente no disponible: {error}</div>;
 if(!data)return <div className="terminal-panel p-5 text-sm text-slate-500"><Activity size={14} className="mr-2 inline animate-pulse"/>Cargando resultados de validación…</div>;
 const enough=data.labeled_60m>=data.minimum_research_sample;
 return <section className="space-y-4">
  <div className={`rounded-3xl border p-4 ${enough?"border-emerald-400/20 bg-emerald-400/[.04]":"border-amber-400/25 bg-amber-400/[.05]"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><div className={`flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] ${enough?"text-emerald-300":"text-amber-300"}`}><FlaskConical size={15}/>{enough?"MUESTRA DE INVESTIGACIÓN DISPONIBLE":"MUESTRA INSUFICIENTE"}</div><p className="mt-1 text-sm text-slate-400">{data.labeled_60m} de {data.minimum_research_sample} casos mínimos a 60 minutos. Hasta alcanzar muestra suficiente, estos porcentajes son descriptivos, no probabilidades.</p></div><span className="rounded-full border border-slate-700 px-3 py-1 text-[10px] font-black text-slate-300">{data.research_status}</span></div></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Stat label="Observaciones" value={String(data.observations)}/><Stat label="Resultados horizonte" value={String(data.horizon_results)}/><Stat label="Casos 60m" value={String(data.labeled_60m)}/><Stat label="Señales operables" value={pct(data.actionable_share_pct)}/><Stat label="SÍ que acabó STOP 60m" value={String(data.diagnostics.false_yes_60m_stop_first)}/><Stat label="Oportunidades omitidas proxy" value={String(data.diagnostics.missed_opportunity_proxy_60m)}/></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{classes.map(c=><div key={c} className="terminal-panel p-4"><div className="text-[9px] font-black uppercase tracking-[.12em] text-slate-600">{c.replaceAll("_"," ")}</div><div className="mt-2 text-3xl font-black text-white">{data.trade_class_counts?.[c]??0}</div><div className="mt-1 text-[10px] text-slate-600">señales registradas</div></div>)}</div>
  <div><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-white">¿Qué pasó después de cada decisión?</h2><span className="text-[10px] text-slate-600">5 · 15 · 30 · 60 · 120 min</span></div><div className="terminal-panel overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-xs"><thead className="border-b border-slate-800 text-[9px] uppercase tracking-[.08em] text-slate-600"><tr><th className="px-3 py-2 text-left">Clase</th><th>Min</th><th>Muestra</th><th>TP1 antes STOP</th><th>MFE medio</th><th>MAE medio</th><th>Retorno dir.</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.trade_class}-${r.horizon_minutes}-${i}`} className="border-t border-slate-900"><td className="px-3 py-3 font-black text-white">{r.trade_class}</td><td className="px-3 py-3 text-center">{r.horizon_minutes}</td><td className="px-3 py-3 text-center">{r.sample}</td><td className="px-3 py-3 text-center font-black text-cyan-200">{pct(r.tp1_before_stop_rate_pct)}</td><td className="px-3 py-3 text-center text-emerald-300">{pct(r.avg_mfe_pct,2)}</td><td className="px-3 py-3 text-center text-rose-300">{pct(r.avg_mae_abs_pct,2)}</td><td className={`px-3 py-3 text-center font-black ${Number(r.avg_directional_return_pct??0)>=0?"text-emerald-300":"text-rose-300"}`}>{pct(r.avg_directional_return_pct,2)}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-8 text-center text-sm text-slate-600">Todavía no existen suficientes horizontes evaluados para formar la tabla.</div>}</div></div>
  <div className="flex gap-2 rounded-2xl border border-cyan-400/15 bg-cyan-400/[.03] p-3 text-[10px] leading-5 text-slate-500"><ShieldCheck size={14} className="mt-0.5 shrink-0 text-cyan-300"/>{data.note} El laboratorio no modifica los filtros automáticamente; primero necesitamos evidencia fuera de muestra.</div>
 </section>
}
function Stat({label,value}:{label:string;value:string}){return <div className="terminal-panel p-3"><div className="text-[9px] font-bold uppercase tracking-[.09em] text-slate-600">{label}</div><div className="mt-2 text-lg font-black text-white">{value}</div></div>}
